image: "node:latest"

stages:
  - install
  - build
cache:
  paths:
    - node_modules

install_job:
  stage: install
  script:
    #    - npm config set registry https://registry.npm.taobao.org
    - npm install --force
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
      allow_failure: true
build_job:
  stage: build
  script:
    - - echo "开始打包"
    - npm run build
    - echo "开始执行build.sh"
    - chmod a+x ./build.sh
    - ./build.sh
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
      allow_failure: true

after_script:
  - echo "Stage：${CI_JOB_STAGE}, Job：${CI_JOB_NAME}, Branch:${CI_COMMIT_BRANCH},CommitMessage:${CI_COMMIT_MESSAGE}, complete！,"
